apiVersion: v1
kind: Pod
metadata:
  name: todoapp-app-pod
  labels:
    app.kubernetes.io/name: todoapp-app-pod
spec:
  containers:
  - name: todoapp-app
    image: todoapp-app:latest
    imagePullPolicy: Never
    ports:
      - containerPort: 5000
  - name: todoapp-db
    image: todoapp-db:latest
    imagePullPolicy: Never
    ports:
      - containerPort: 3306
