apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-app-depl
  labels:
    app.kubernetes.io/name: todoapp-app-depl
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: todoapp-app-depl
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todoapp-app-depl
    spec:
      containers:
        - name: todoapp-app
          image: todoapp-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
        - name: todoapp-db
          image: todoapp-db:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
